### PR TITLE
Handle Execute limit correctly by sending PortalSuspended

### LINKED ISSUE #137: Execute limit enforcement is incorrect, it should not throw an error
The PR https://github.com/jeroenrinzema/psql-wire/pull/115 tried to implement the limit field of the Execute message. But the way it did that is incorrect. It's now throwing an error whenever the limit is reached, but that's not what is supposed to happen. These are the protocol docs:

> Once a portal exists, it can be executed using an Execute message. The Execute message specifies the portal name (empty string denotes the unnamed portal) and a maximum result-row count (zero meaning “fetch all rows”). The result-row count is only meaningful for portals containing commands that return row sets; in other cases the command is always executed to completion, and the row count is ignored. The possible responses to Execute are the same as those described above for queries issued via simple query protocol, except that Execute doesn't cause ReadyForQuery or RowDescription to be issued.
>
> If Execute terminates before completing the execution of a portal (due to reaching a nonzero result-row count), it will send a PortalSuspended message; the appearance of this message tells the frontend that another Execute should be issued against the same portal to complete the operation. The CommandComplete message indicating completion of the source SQL command is not sent until the portal's execution is completed. Therefore, an Execute phase is always terminated by the appearance of exactly one of these messages: CommandComplete, EmptyQueryResponse (if the portal was created from an empty query string), ErrorResponse, or PortalSuspended.

Source: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

So instead it should be returning a `PortalSuspended` message when the limit is reached, and then it can receive a new Execute message for the same portal to continue reading the resultset from that point onward. It can do so, to read the result in batches until the result is complete.

I'm opening this issue to discuss how we should go about solving this. A few options I can think of:

1. Revert #115, I think having Execute return all rows is probably better than throwing an error whenever a client uses this feature. 
2. Change the `handler` API so that the prepared statement function can save and restore its state somehow.
3. Change the `handler` API so that it should provide an iterator that generates rows using the [`Seq` interface](https://pkg.go.dev/iter). Then have handleExecute consume up to the limit and store the iterator state in the portal until the next iteration. 
4. Keep the `handler` API the same and run the handler in a go routine, and consume the rows from a channel. 

I'd prefer option 3, but the downside is that that would break all existing implementations. Do you think that's a problem? If so, I guess we could make it so that the old handler API falls back to either option 1 or 4.

### PR DESCRIPTION
**Pull request by JelteF**
The PR #115 tried to implement the limit field of the Execute message. But the way it did that is incorrect. It's now throwing an error whenever the limit is reached, but that's not what is supposed to happen. These are the protocol docs:

> Once a portal exists, it can be executed using an Execute message. The Execute message specifies the portal name (empty string denotes the unnamed portal) and a maximum result-row count (zero meaning “fetch all rows”). The result-row count is only meaningful for portals containing commands that return row sets; in other cases the command is always executed to completion, and the row count is ignored. The possible responses to Execute are the same as those described above for queries issued via simple query protocol, except that Execute doesn't cause ReadyForQuery or RowDescription to be issued.
>
> If Execute terminates before completing the execution of a portal (due to reaching a nonzero result-row count), it will send a PortalSuspended message; the appearance of this message tells the frontend that another Execute should be issued against the same portal to complete the operation. The CommandComplete message indicating completion of the source SQL command is not sent until the portal's execution is completed. Therefore, an Execute phase is always terminated by the appearance of exactly one of these messages: CommandComplete, EmptyQueryResponse (if the portal was created from an empty query string), ErrorResponse, or PortalSuspended.

Source: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

So instead it should be returning a `PortalSuspended` message when the limit is reached, and then it can receive a new Execute message for the same portal to continue reading the resultset from that point onward. It can do so, to read the result in batches until the result is complete.

This PR implements that **without changing the handler API**. This is done by using `iter.Pull` to convert the "push-style" iteration API of the handler into a "pull-style" one that can be paused and resumed when necessary.

Getting this to work with the parallel pipeline execution (introduced in #123) was a bit tricky, because Execute messages that use the same portal must now be executed sequentially. This is handled by the `pending` channel that they set on the portal to create a chain of go routines that wait on each other. In practice it seems unlikely that people will use `Execute` on the same portal in a single batch of pipelined messages (i.e. why would the not simply read the full amount right away). Instead the more common case that would be run into is a `Close` message arriving in the same pipeline batch. This should clean up the portal and its associated iterator, but it should not do so before the `Execute` has actually completed. 

Fixes #137
Related to #115
Related to #123

### CODE REVIEW

File: cache.go [hunk 1]
```diff
@@ -60,21 +69,143 @@ func (cache *DefaultStatementCache) Get(ctx context.Context, name string) (*Stat
...
+				ctx:     ctx,
+				session: session,
+				columns: p.statement.columns,
+				formats: p.formats,
+				reader:  reader,
+				client:  writer,
+				yield:   yield,
+				tag:     &p.tag,
+			}
+			err := p.statement.fn(ctx, dw, p.parameters)
```
Comment (jeroenrinzema) [inline cache.go:164]: I noticed we are getting a race error when calling `.fn()` due to the `*pgtype.Map` being shared. We will have to clone the `pgtype.Map` in each goroutine.

File: cache.go [hunk 2]
```diff
@@ -60,21 +69,143 @@ func (cache *DefaultStatementCache) Get(ctx context.Context, name string) (*Stat
...
+}
+
+func (p *Portal) execute(ctx context.Context, limit Limit, reader *buffer.Reader, writer *buffer.Writer) error {
+	if p.done {
+		// Re-executing an already completed portal simply returns the tag or
+		// error again.
+		if p.err != nil {
+			return p.err
+		}
+		return commandComplete(writer, p.tag)
```
Comment (jeroenrinzema) [inline cache.go:144]: Looking at the code `p.tag` is never actually updated by `dataWriter.Complete`. The `dataWriter.tag` field is initialized as `&p.tag`, but Complete does `writer.tag = &description` which reassigns the pointer itself to the local parameter rather than writing through it with *writer.tag = description.

I see there is no test for this at the moment to check the tag value. A test could confirm whether the tag is properly assigned.

**Review by jeroenrinzema — CHANGES_REQUESTED** [review]
Thanks for the PR @JelteF , it is a nice and clean implementation properly implementing PortalSuspended.

File: cache.go (hunk 1 above)
Comment (JelteF) [reply cache.go:164]: Ah yeah, I didn't realize that. It changed because I removed the QueuedDataWriter, and started encoding in the `Execute` go routines directly to a bytes buffer.

Copying the map indeed fixed this.

File: cache.go (hunk 2 above)
Comment (JelteF) [reply cache.go:144]: Fixed and added some tests.

**Comment by JelteF** [comment]
To be clear, this PR includes #136.

**Review by jeroenrinzema — APPROVED** [review]
